search_path: ./
output_path: ./wire
package: wire
init_types:
    - App
    - Server
enable_cache: true
parallel: 0
exclude_dirs:
    - vendor
    - testdata
    - .git
include_only: []
watch: false
watch_ignore:
    - '*.gen.go'
    - wire_gen.go
