// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package inject

import (
	"github.com/google/wire"
	"github.com/spelens-gud/gutowire/example/dependencies"
)

var InitSet = wire.NewSet(
	wire.Struct(new(dependencies.Test), "*"),
)
