package internal

// setTemplate Wire Set 的代码生成模板
// 用于生成类似 var AnimalsSet = wire.NewSet(...) 的代码.
var setTemplate = `// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package {{ .Package }}

import (
	"github.com/google/wire"
)

var {{ .SetName }} = wire.NewSet({{ range $Item := .Items}} 
	{{ $Item }},
    {{ end }}
)
`

// initTemplateHead 初始化函数文件的头部模板.
var initTemplateHead = `// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package %s
`

// initItemTemplate 单个初始化函数的模板
// 生成类似 func InitializeZoo() (*Zoo, func(), error) 的函数.
var initItemTemplate = `
func Initialize%s(%s) (%s, func(), error) {
	panic(wire.Build(Sets))
}
`
