package generator

import (
	"text/template"
)

// Element struct    表示一个可注入的组件(结构体或函数).
type Element struct {
	Name        string   // 组件名称，如 Zoo、Cat
	Constructor string   // 构造函数名称，如 NewZoo、InitCat
	Fields      []string // 结构体字段列表（用于 config 模式）
	Implements  []string // 实现的接口列表
	Pkg         string   // 所在包名
	PkgPath     string   // 完整的包导入路径
	InitWire    bool     // 是否标记为 @autowire.init
	ConfigWire  bool     // 是否标记为 @autowire.config
}

// WireSet struct    表示一个 Wire Set 的配置信息.
type WireSet struct {
	Package string   // 包名
	Items   []string // Set 中包含的所有项（构造函数、结构体等）
	SetName string   // Set 的名称，如 AnimalsSet
}

// SetTemp 预编译的 Set 模板，用于快速生成代码.
var SetTemp = template.Must(template.New("").Parse(setTemplate))

// setTemplate Wire Set 的代码生成模板
// 用于生成类似 var AnimalsSet = wire.NewSet(...) 的代码.
var setTemplate = `// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package {{ .Package }}

import (
	"github.com/google/wire"
)

var {{ .SetName }} = wire.NewSet({{ range $Item := .Items}} 
	{{ $Item }},
    {{ end }}
)
`

// initTemplateHead 初始化函数文件的头部模板.
var initTemplateHead = `// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package %s
`

// initItemTemplate 单个初始化函数的模板
// 生成类似 func InitializeZoo() (*Zoo, func(), error) 的函数.
var initItemTemplate = `
func Initialize%s(%s) (%s, func(), error) {
	panic(wire.Build(Sets))
}
`
